### ISSUE TITLE
loopTracks is always true

### ISSUE THREAD

**Issue by notpushkin** [jescalan/listplayer#1]
This line:

```js
this.loopTracks = options.loopTracks || true
```

actually sets `loopTracks` to true even if `options.loopTracks` is false. The same issue with `progressThroughTracks`.

And an unrelated semi-issue: what is the intended behaviour when user manually changes options on the player object? I. e.

```js
const player = new ListPlayer({ loopTracks: true, progressThroughTracks: true })
// ... sometime later ...
player.loopTracks = false
player.progressThroughTracks = false
```

In this example, tracks looping will actually be disabled but the "progress" behaviour wouldn't (as it is made as an event handler which is already attached).

**Comment by jescalan** [comment]
Good catch! Pretty simple fix, want to submit a PR to close those out?

And for the second issue, could be fixed by moving some of the logic in the constructor to getter/setters. I can take this one if you do the first? 😉

**Comment by notpushkin** [comment]
Probably tomorrow then, just too much Javascript for me today :)

**Comment by jescalan** [comment]
@iamale haha totally understand 👬

**Comment by notpushkin** [comment]
As for the second issue, the fix can be actually as simple as

```js
this.el.addEventListener('ended', () => {
  if (this.progressThroughTracks) {
    this.next()
    this.play()
  }
})
```

Although it could have a small performance penalty (one `if` check per track), I think it is much more cleaner than dealing with getters/setters.

Should I include it in the PR too?
